# Load packages
library(dplyr)

# Load the data generated by 00_rawdata.R
clean_data <- readRDS("./bin/cleaned_data.rds")

#=========================================
# 2. Calculating statistics
#=========================================
# a. Generate data frame with N, mean, sd, and se
stats <- clean_data %>%
  group_by(experiment, cell_line, time) %>%
  summarise(
    N = n(), # number of RLUs
    mean = mean(RLU),
    sd = sd(RLU),
    se = sd / sqrt(N)
  )

# b. Experimental differences in starting number of cells
normalized_stats <- stats %>%
  group_by(experiment, cell_line) %>%
  mutate(mean = mean - min(mean)) %>%
  ungroup()

# ----------------------------------
# Save processed statistics
# ----------------------------------
saveRDS(stats, "./bin/stats.rds")
saveRDS(normalized_stats, "./bin/normalized.rds")
